// const endpointRoot = "https://todoie.herokuapp.com";
const endpointRoot = "";
export const URL_FETCH_USER = endpointRoot + "/api/current_user";
export const URL_LOGIN = endpointRoot + "/api/login";
export const URL_LOGOUT = endpointRoot + "/api/logout";
export const URL_SIGNUP = endpointRoot + "/api/signup";
export const URL_GETUSERDATA = endpointRoot + "/api/getUserData";
export const URL_UPDATE_TODO = endpointRoot + "/api/updateTodo";
export const URL_ADD_GROUP = endpointRoot + "/api/addGroup";
